Repository uktrade/data-hub-api, pull requests merged in 2024-10, with the labels that each got.

#5686 Dependencies 8th Oct 2024
  requirements-dev.in
  requirements-dev.txt
  requirements.in
  requirements.txt
Labels: dependencies

#5693 CLS2-954 Link EYBLead and InvestmentProject via M2M
  datahub/cleanup/management/commands/delete_old_records.py
  datahub/cleanup/test/commands/test_delete_old_records.py
  datahub/investment_lead/migrations/0005_eyblead_investment_projects.py
  datahub/investment_lead/models.py
  datahub/investment_lead/serializers.py
  datahub/investment_lead/test/factories.py
Labels: enhancement

#5707 CLS2-988 Link EYB Lead when Investment Project is created
  datahub/investment/project/admin.py
  datahub/investment/project/serializers.py
  datahub/investment/project/test/test_views.py
  datahub/investment_lead/admin.py
Labels: enhancement

#5720 Fix a link to the release notes tab
  docs/Deployments.md
Labels: bug

#5724 Fix EYB lead admin page crashing
  datahub/investment_lead/admin.py
Labels: bug

#5735 Dependencies 28th Oct 2024
  requirements-dev.in
  requirements-dev.txt
  requirements.in
  requirements.txt
Labels: dependencies

#5744 CLS2-1015 Expose Investment Projects in EYB Lead retrieve serializer
  datahub/investment_lead/serializers.py
  datahub/investment_lead/test/conftest.py
  datahub/investment_lead/test/utils.py
Labels: enhancement
