Repository uktrade/data-hub-api, pull requests merged in 2024-11, with the labels that each got.

#5750 CLS2-1014: Default ordering for EYB leads
  datahub/investment_lead/test/test_views.py
  datahub/investment_lead/views.py
Labels: enhancement

#5770 Fix/cls2-1038 DUNS number empty string
  datahub/investment_lead/serializers.py
  datahub/investment_lead/services.py
  datahub/investment_lead/test/test_services.py
Labels: bug

#5773 Tet 851 company activity search great data
  datahub/company_activity/migrations/0013_alter_greatexportenquiry_data_enquiry_squashed_0015_alter_companyactivity_activity_source.py
  datahub/company_activity/models/company_activity.py
  datahub/company_activity/models/great.py
  datahub/company_activity/tasks/sync.py
  datahub/company_activity/tests/factories.py
  datahub/company_activity/tests/models/test_great_export_enquiry.py
  datahub/company_activity/tests/test_tasks/test_great_task.py
  datahub/search/company_activity/apps.py
  datahub/search/company_activity/dict_utils.py
  datahub/search/company_activity/fields.py
  datahub/search/company_activity/models.py
  datahub/search/company_activity/signals.py
  datahub/search/company_activity/test/test_dict_utils.py
  datahub/search/company_activity/test/test_models.py
  datahub/search/company_activity/test/test_signals.py
Labels: don't merge

#5789 CLS2-1033: Add EYB lead source to Company Activity model
  datahub/company_activity/migrations/0016_companyactivity_eyb_lead_and_more.py
  datahub/company_activity/models/company_activity.py
  datahub/company_activity/tests/factories.py
Labels: enhancement

#5816 CLS2-1035 Sync CompanyActivity with EYB Lead on save
  datahub/cleanup/test/commands/test_delete_orphaned_versions.py
  datahub/company_activity/tasks/sync.py
  datahub/company_activity/tests/test_tasks/test_eyb_lead_tasks.py
  datahub/company_activity/tests/test_tasks/test_order_task.py
  datahub/investment_lead/models.py
  datahub/investment_lead/test/test_models.py
Labels: enhancement

#5817 Filter EYB leads by both `EYBLead.company_name` and `EYBLead.company.name`
  datahub/investment_lead/test/test_views.py
  datahub/investment_lead/views.py
Labels: bug

#5825 FEATURE/CLS2-1034 Add EYBLead to Company Activity - search
  datahub/search/company_activity/apps.py
  datahub/search/company_activity/dict_utils.py
  datahub/search/company_activity/fields.py
  datahub/search/company_activity/models.py
  datahub/search/company_activity/signals.py
  datahub/search/company_activity/test/test_dict_utils.py
  datahub/search/company_activity/test/test_models.py
  datahub/search/company_activity/test/test_signals.py
  datahub/search/company_activity/test/test_views.py
Labels: enhancement

#5828 CLS2-1031 Add EYB Lead to Company Activity and Opensearch
  datahub/cleanup/test/commands/test_delete_orphaned_versions.py
  datahub/company_activity/migrations/0018_companyactivity_eyb_lead_and_more.py
  datahub/company_activity/models/company_activity.py
  datahub/company_activity/tasks/sync.py
  datahub/company_activity/tests/factories.py
  datahub/company_activity/tests/test_tasks/test_eyb_lead_tasks.py
  datahub/company_activity/tests/test_tasks/test_order_task.py
  datahub/investment_lead/models.py
  datahub/investment_lead/test/test_models.py
  datahub/search/company_activity/apps.py
  datahub/search/company_activity/dict_utils.py
  datahub/search/company_activity/fields.py
  datahub/search/company_activity/models.py
  datahub/search/company_activity/signals.py
  datahub/search/company_activity/test/test_dict_utils.py
  datahub/search/company_activity/test/test_models.py
  datahub/search/company_activity/test/test_signals.py
  datahub/search/company_activity/test/test_views.py
Labels: enhancement

#5830 CLS2-1069 Fix marketing data ingestion bug
  datahub/investment_lead/tasks/ingest_eyb_marketing.py
  datahub/investment_lead/test/test_tasks/test_ingest_eyb_marketing.py
Labels: bug
